Fix user and conference removal
jolicode/starfleet pull request #118
Opened 2021-01-29 15:07 UTC by HedicGuibert

Refs https://github.com/jolicode/starfleet/issues/93

Set `null` on related entities when removing a user or a conference

2021-01-29 16:20 UTC, welcoMattic requested changes

2021-01-29 16:20 UTC, welcoMattic commented on src/Controller/Admin/AdminController.php
> +        $this->em->flush();
You must centralize the duplicated code in a private method then call it in the 3 remove*ConferencesEntity methods

2021-01-30 15:22 UTC, welcoMattic approved these changes

2021-02-08 10:04 UTC, lyrixx commented on src/Controller/Admin/AdminController.php
> +    protected ?LoggerInterface $logger;
There is always a logger defined

2021-02-08 10:04 UTC, lyrixx commented on src/Controller/Admin/AdminController.php
> +        $this->em->flush();
If you configure property the DB (and doctrine), The DB will do it for you.
Here, you load tons of data ; you should not. The DB must handle that

2021-02-08 18:41 UTC, lyrixx reviewed
Acutally, I don't understand the goal of this PR.

Why do we want to support conference removal?
And user removal?

2021-02-08 18:41 UTC, lyrixx commented on migrations/Version20210208110825.php
> +final class Version20210208110825 extends AbstractMigration
Let's merge this migration with the previous one

2021-02-08 18:41 UTC, lyrixx commented on src/Controller/Admin/AdminController.php
> +        $this->logger = $logger ?: new NullLogger();
Looks like this can be revert

2021-02-08 18:41 UTC, lyrixx commented on src/Entity/Participation.php
> +    private ?Conference $conference;
It does not make sens to me. Why would we want to remove a Conference where someone attended?

2021-02-09 08:45 UTC, HedicGuibert commented
This addresses https://github.com/jolicode/starfleet/issues/93 where we decided to set null when a user or a conference is deleted

2021-02-09 10:46 UTC, HedicGuibert commented
So as mentioned in https://github.com/jolicode/starfleet/issues/93 I ended up reverting everything and only disabling the possibility to delete a user or a conference

2021-02-09 11:25 UTC, lyrixx approved these changes
Thanks

2021-02-09 11:25 UTC, merged