Fix conference_show route only working for attended conferences
jolicode/starfleet pull request #155
Opened 2021-03-16 16:49 UTC by HedicGuibert

Currently, almost all slack links are not working because the conference_show route only works with attended conferences.

This will allow all conferences to work with the show_conference route.

2021-03-16 16:53 UTC, welcoMattic approved these changes

2021-03-16 17:01 UTC, lyrixx approved these changes
Thanks

2021-03-16 17:01 UTC, lyrixx requested changes

2021-03-16 17:01 UTC, lyrixx commented on src/Controller/ConferenceController.php
> -        $conference = $conferenceRepository->findOneAttended($slug);
This method is not use anymore. It must be deleted

2021-03-17 20:48 UTC, lyrixx approved these changes

2021-03-17 20:48 UTC, merged